// Generated by codegen.py

struct PointLightData {
    float3 position;
    float intensity;
    float3 color;
    float radius;
};

struct ParticleGPUData {
    float3 position;
    float age;
    float3 velocity;
    float maxLifetime;
    float4 color;
    float3 rotation;
    float scale;
    uint modelIndex;
    uint textureIndex;
    uint entityID;
    uint postProcessFlags;
};

struct SceneData {
    row_major float4x4 view;
    row_major float4x4 viewProj;
    float3 cameraPos;
    uint numPointLights;
    float dirLightIntensity;
    float3 dirLightColor;
    float3 dirLightDirection;
    float screenWidth;
    float screenHeight;
    float nearZ;
    float farZ;
    uint selectedEntityID;
};

struct TextData {
    row_major float4x4 world;
    float4 color;
    float2 uvMin;
    float2 uvMax;
    uint textureIndex;
    uint padding;
    uint _final_pad0[2];
};

struct MeshInfo {
    uint vertexOffset;
    uint indexOffset;
    uint vertexCount;
    uint indexCount;
    uint meshCount;
    uint _final_pad0[3];
};

struct BoneData {
    row_major float4x4 transform;
};

struct SkinningParams {
    uint vertexCount;
    uint inputVertexOffset;
    uint outputVertexOffset;
    uint boneOffset;
    uint skinningEnabled;
    uint _final_pad0[3];
};

struct BatchData {
    uint instanceOffset;
    uint _final_pad0[3];
};

struct SpriteData {
    row_major float4x4 world;
    float4 color;
    uint textureIndex;
    uint isBillboard;
    uint entityID;
    uint postProcessFlags;
};

struct BoneWeightData {
    uint boneIndices[4];
    float4 boneWeights;
};

struct InstanceData {
    row_major float4x4 world;
    float4 aabbMin;
    float4 aabbMax;
    float4 baseColor;
    uint modelIndex;
    uint textureIndex;
    uint vertexOffset;
    uint entityID;
    uint postProcessFlags;
    uint unused_pad[3];
};

struct MaterialData {
    float4 baseColor;
};

