// Generated by codegen.py

struct SceneData {
    float4x4 viewProj;
};

struct InstanceData {
    float4x4 world;
    float4 baseColor;
    uint textureIndex;
    float3 padding;
};

struct MaterialData {
    float4 baseColor;
};

struct Transform {
    float3 position;
    uint _pad0[1];
    float3 rotation;
    uint _pad1[1];
    float3 scale;
    uint _final_pad2[1];
};

struct MeshRenderer {
    uint modelIndex;
    uint materialIndex;
    uint _final_pad0[2];
};

