// Generated by codegen.py

struct TextRenderer {
    uint text[64];
    uint fontIndex;
    uint _pad0[3];
    float4 color;
    float size;
    uint isScreenSpace;
    uint _final_pad1[2];
};

struct SkinnedMeshRenderer {
    uint modelIndex;
    uint materialIndex;
    uint skeletonIndex;
    uint postProcessFlags;
    uint internalVertexOffset;
    uint _final_pad0[3];
};

struct SceneData {
    row_major float4x4 view;
    row_major float4x4 viewProj;
    float3 cameraPos;
    uint numPointLights;
    float dirLightIntensity;
    float3 dirLightColor;
    float3 dirLightDirection;
    float screenWidth;
    float screenHeight;
    float nearZ;
    float farZ;
    uint _final_pad0[1];
};

struct Transform {
    uint parent;
    float3 position;
    float3 rotation;
    uint _pad0[1];
    float3 scale;
    uint _pad1[1];
    row_major float4x4 world;
};

struct TextData {
    row_major float4x4 world;
    float4 color;
    float2 uvMin;
    float2 uvMax;
    uint textureIndex;
    uint padding;
    uint _final_pad0[2];
};

struct Camera {
    float fov;
    float nearZ;
    float farZ;
    uint _final_pad0[1];
};

struct PointLight {
    float3 color;
    float intensity;
    float radius;
    uint _final_pad0[3];
};

struct ParticleEmitter {
    uint count;
    float speed;
    float speedRandom;
    float lifetime;
    float lifetimeRandom;
    float spreadAngle;
    float gravity;
    uint _pad0[1];
    float4 startColor;
    float4 endColor;
    float startScale;
    float endScale;
    uint modelIndex;
    uint textureIndex;
    uint bufferIndex;
    uint _final_pad1[3];
};

struct DirectionalLight {
    float3 color;
    float intensity;
    float3 direction;
    uint _final_pad0[1];
};

struct InstanceData {
    row_major float4x4 world;
    float4 aabbMin;
    float4 aabbMax;
    float4 baseColor;
    uint modelIndex;
    uint textureIndex;
    uint vertexOffset;
    uint entityID;
    uint postProcessFlags;
    uint unused_pad[3];
};

struct PointLightData {
    float3 position;
    float intensity;
    float3 color;
    float radius;
};

struct ParticleGPUData {
    float3 position;
    float age;
    float3 velocity;
    float maxLifetime;
    float4 color;
    float3 rotation;
    float scale;
    uint modelIndex;
    uint textureIndex;
    uint entityID;
    uint postProcessFlags;
};

struct MeshInfo {
    uint vertexOffset;
    uint indexOffset;
    uint vertexCount;
    uint indexCount;
    uint meshCount;
    uint _final_pad0[3];
};

struct SpriteRenderer {
    uint textureIndex;
    uint _pad0[3];
    float4 color;
    float2 size;
    uint isBillboard;
    uint _final_pad1[1];
};

struct BoneData {
    row_major float4x4 transform;
};

struct ScriptComponent {
    uint2 gcHandle;
    uint typeId;
    uint _final_pad0[1];
};

struct MeshRenderer {
    uint modelIndex;
    uint materialIndex;
    uint postProcessFlags;
    uint _final_pad0[1];
};

struct Skybox {
    uint textureIndex;
    uint _final_pad0[3];
};

struct SpriteData {
    row_major float4x4 world;
    float4 color;
    uint textureIndex;
    uint isBillboard;
    uint entityID;
    uint postProcessFlags;
};

struct MaterialData {
    float4 baseColor;
};

struct BoneWeightData {
    uint boneIndices[4];
    float4 boneWeights;
};

struct SkinningParams {
    uint vertexCount;
    uint inputVertexOffset;
    uint outputVertexOffset;
    uint boneOffset;
    uint skinningEnabled;
    uint _final_pad0[3];
};

