// Generated by codegen.py

struct SceneData {
    float4x4 viewProj;
};

struct InstanceData {
    float4x4 world;
    float4 baseColor;
    uint textureIndex;
};

struct MaterialData {
    float4 baseColor;
    uint textureIndex;
    uint _final_pad0[3];
};

