import yaml
import os

# Configuration
INPUT_FILE = "Project/Tools/schema.yaml"
CPP_OUTPUT = "Project/Schema/Schema.h"
HLSL_OUTPUT = "Project/Assets/Shader/Schema/Schema.hlsli"

TYPE_MAP_CPP = {
    "float4x4": "Engine::Math::Matrix4x4",
    "float4": "Engine::Math::Vector4",
    "float3": "Engine::Math::Vector3",
    "float2": "Engine::Math::Vector2",
    "float": "float",
    "uint32": "uint32_t",
}

TYPE_MAP_HLSL = {
    "float4x4": "float4x4",
    "float4": "float4",
    "float3": "float3",
    "float2": "float2",
    "float": "float",
    "uint32": "uint",
}

TYPE_SIZES = {
    "float4x4": 64,
    "float4": 16,
    "float3": 12,
    "float2": 8,
    "float": 4,
    "uint32": 4,
}

TYPE_ALIGNMENTS = {
    "float4x4": 16,
    "float4": 16,
    "float3": 4, # HLSL packs float3 into 4-byte slots, but it can't cross 16-byte boundary
    "float2": 4,
    "float": 4,
    "uint32": 4,
}

def generate():
    if not os.path.exists(INPUT_FILE):
        print(f"Error: {INPUT_FILE} not found.")
        return

    with open(INPUT_FILE, "r") as f:
        schema = yaml.safe_load(f)

    cpp_content = "#pragma once\n#include \"Engine/Core/Math/Math.h\"\n#include <cstdint>\n\nnamespace Engine::GeneratedSchema {\n\n"
    hlsl_content = "// Generated by codegen.py\n\n"

    for type_name, info in schema.get("types", {}).items():
        is_cb = info.get("type") == "ConstantBuffer"
        fields = info.get("fields", [])
        
        cpp_struct = f"struct {type_name} {{\n"
        hlsl_struct = f"struct {type_name} {{\n"
        
        current_offset = 0
        pad_index = 0
        
        for field in fields:
            f_name = field["name"]
            f_type = field["type"]
            f_size = TYPE_SIZES[f_type]
            f_align = TYPE_ALIGNMENTS[f_type]
            
            # HLSL Packing Rules:
            # 1. Elements cannot cross 16-byte boundaries.
            # 2. If it doesn't fit in the current 16-byte chunk, move to next.
            if is_cb:
                remaining_in_chunk = 16 - (current_offset % 16)
                if f_size > remaining_in_chunk:
                    # Move to next 16-byte boundary
                    pad_size = remaining_in_chunk
                    if pad_size > 0 and pad_size < 16: # If pad_size == 16, we are already at boundary
                        if pad_size % 4 == 0:
                            cpp_struct += f"    uint32_t _pad{pad_index}[{pad_size // 4}];\n"
                            hlsl_struct += f"    uint _pad{pad_index}[{pad_size // 4}];\n"
                        else:
                            cpp_struct += f"    uint8_t _pad{pad_index}[{pad_size}];\n"
                            hlsl_struct += f"    uint8_t _pad{pad_index}[{pad_size}];\n"
                        pad_index += 1
                        current_offset += pad_size

            cpp_struct += f"    {TYPE_MAP_CPP[f_type]} {f_name};\n"
            hlsl_struct += f"    {TYPE_MAP_HLSL[f_type]} {f_name};\n"
            current_offset += f_size

        # Final padding for ConstantBuffer to multiple of 16
        if is_cb and current_offset % 16 != 0:
            pad_size = 16 - (current_offset % 16)
            if pad_size % 4 == 0:
                cpp_struct += f"    uint32_t _final_pad{pad_index}[{pad_size // 4}];\n"
                hlsl_struct += f"    uint _final_pad{pad_index}[{pad_size // 4}];\n"
            else:
                cpp_struct += f"    uint8_t _final_pad{pad_index}[{pad_size}];\n"
            current_offset += pad_size

        cpp_struct += "};\n\n"
        hlsl_struct += "};\n\n"
        
        cpp_content += cpp_struct
        hlsl_content += hlsl_struct

    cpp_content += "} // namespace Engine::GeneratedSchema\n"

    # Write files
    os.makedirs(os.path.dirname(CPP_OUTPUT), exist_ok=True)
    os.makedirs(os.path.dirname(HLSL_OUTPUT), exist_ok=True)

    with open(CPP_OUTPUT, "w") as f:
        f.write(cpp_content)
    with open(HLSL_OUTPUT, "w") as f:
        f.write(hlsl_content)

    print(f"Generated {CPP_OUTPUT} and {HLSL_OUTPUT}")

if __name__ == "__main__":
    generate()
