import yaml
import os
import glob

# Configuration
INPUT_DIR = "Project/Tools/Schema"
CPP_OUTPUT_DIR = "Project/Schema"
HLSL_OUTPUT_DIR = "Project/Assets/Shader/Schema"
CS_OUTPUT_DIR = "SubProjects/ONEngine.Scripting/Generated"

TYPE_MAP_CPP = {
    "float4x4": "Engine::Math::Matrix4x4",
    "float4": "Engine::Math::Vector4",
    "float3": "Engine::Math::Vector3",
    "float2": "Engine::Math::Vector2",
    "float": "float",
    "uint32": "uint32_t",
    "uint64": "uint64_t",
    "string": "char",
}

TYPE_MAP_HLSL = {
    "float4x4": "row_major float4x4",
    "float4": "float4",
    "float3": "float3",
    "float2": "float2",
    "float": "float",
    "uint32": "uint",
    "uint64": "uint2", 
}

TYPE_MAP_CS = {
    "float4x4": "Matrix4x4",
    "float4": "Vector4",
    "float3": "Vector3",
    "float2": "Vector2",
    "float": "float",
    "uint32": "uint",
    "uint64": "ulong",
}

TYPE_SIZES = {
    "float4x4": 64,
    "float4": 16,
    "float3": 12,
    "float2": 8,
    "float": 4,
    "uint32": 4,
    "uint64": 8,
    "string": 256,
}

def generate_serialization(type_name, fields):
    to_json = "inline void to_json(nlohmann::json& j, const {}& v) {{\n".format(type_name)
    to_json += "    j = nlohmann::json{\n"
    
    from_json = "inline void from_json(const nlohmann::json& j, {}& v) {{\n".format(type_name)
    
    for field in fields:
        f_name = field["name"]
        f_type = field["type"]
        f_count = field.get("count", 1)
        
        if f_type == "string":
            to_json += "        {{\"{}\", std::string(v.{})}},\n".format(f_name, f_name)
            from_json += "    if (j.contains(\"{}\")) {{ std::string s = j.at(\"{}\").get<std::string>(); strncpy(v.{}, s.c_str(), sizeof(v.{}) - 1); v.{}[sizeof(v.{}) - 1] = '\\0'; }}\n".format(f_name, f_name, f_name, f_name, f_name, f_name)
        elif f_count > 1:
            to_json += "        {{\"{}\", v.{}}},\n".format(f_name, f_name)
            from_json += "    if (j.contains(\"{}\")) {{ auto& arr = j.at(\"{}\"); for(int i=0; i<{}; ++i) v.{}[i] = arr.at(i).get<{}>(); }}\n".format(f_name, f_name, f_count, f_name, TYPE_MAP_CPP[f_type])
        else:
            to_json += "        {{\"{}\", v.{}}},\n".format(f_name, f_name)
            from_json += "    if (j.contains(\"{}\")) v.{} = j.at(\"{}\").get<{}>();\n".format(f_name, f_name, f_name, TYPE_MAP_CPP[f_type])
            
    to_json += "    };\n}\n"
    from_json += "}\n"
    return to_json + "\n" + from_json

def process_file(yaml_path):
    base_name = os.path.splitext(os.path.basename(yaml_path))[0]
    
    with open(yaml_path, "r") as f:
        schema = yaml.safe_load(f)

    cpp_content = "#pragma once\n#include \"Engine/Core/Math/Math.h\"\n#include <cstdint>\n#include <nlohmann/json.hpp>\n#include <cstring>\n#include <string>\n\n"
    hlsl_content = "// Generated by codegen.py\n\n"
    cs_content = "using System.Runtime.InteropServices;\nusing ONEngine.Scripting.Math;\n\nnamespace ONEngine.Scripting.Generated\n{\n"

    # Separate logic for Components (they usually go into Engine::ECS)
    is_component_file = base_name.lower() == "components"
    namespace = "Engine::ECS" if is_component_file else "Engine::GeneratedSchema"
    
    cpp_content += "namespace {} {{\n\n".format(namespace)
    
    serialization_content = ""
    has_hlsl_data = False

    for type_name, info in schema.get("types", {}).items():
        type_category = info.get("type")
        is_comp = type_category == "Component"
        fields = info.get("fields", [])
        
        cpp_struct_body = ""
        hlsl_struct_body = ""
        cs_struct_body = ""
        current_offset = 0
        pad_index = 0
        
        for field in fields:
            f_name = field["name"]
            f_type = field["type"]
            f_size = TYPE_SIZES[f_type]
            
            if f_type != "string":
                remaining_in_chunk = 16 - (current_offset % 16)
                if f_size > remaining_in_chunk and remaining_in_chunk < 16:
                    pad_size = remaining_in_chunk
                    cpp_struct_body += "    uint8_t _pad{}[{}];\n".format(pad_index, pad_size)
                    hlsl_struct_body += "    uint _pad{}[{}];\n".format(pad_index, pad_size // 4)
                    cs_struct_body += "        private unsafe fixed byte _pad{}[{}];\n".format(pad_index, pad_size)
                    pad_index += 1
                    current_offset += pad_size

            if f_type == "string":
                cpp_struct_body += "    char {}[256];\n".format(f_name)
                hlsl_struct_body += "    uint {}[64];\n".format(f_name)
                cs_struct_body += "        public unsafe fixed byte {}[256];\n".format(f_name)
            else:
                f_count = field.get("count", 1)
                if f_count > 1:
                    cpp_struct_body += "    {} {}[{}];\n".format(TYPE_MAP_CPP[f_type], f_name, f_count)
                    hlsl_struct_body += "    {} {}[{}];\n".format(TYPE_MAP_HLSL[f_type], f_name, f_count)
                    cs_struct_body += "        public unsafe fixed {} {}[{}];\n".format(TYPE_MAP_CS[f_type], f_name, f_count)
                    f_size *= f_count
                else:
                    cpp_struct_body += "    {} {};\n".format(TYPE_MAP_CPP[f_type], f_name)
                    hlsl_struct_body += "    {} {};\n".format(TYPE_MAP_HLSL[f_type], f_name)
                    cs_struct_body += "        public {} {};\n".format(TYPE_MAP_CS[f_type], f_name)
            current_offset += f_size

        if current_offset % 16 != 0:
            pad_size = 16 - (current_offset % 16)
            cpp_struct_body += "    uint8_t _final_pad{}[{}];\n".format(pad_index, pad_size)
            hlsl_struct_body += "    uint _final_pad{}[{}];\n".format(pad_index, pad_size // 4)
            cs_struct_body += "        private unsafe fixed byte _final_pad{}[{}];\n".format(pad_index, pad_size)
            current_offset += pad_size

        cpp_content += "struct {} {{\n{}}};\n\n".format(type_name, cpp_struct_body)
        cs_content += "    [StructLayout(LayoutKind.Sequential)]\n    public struct {}\n    {{\n{}{}    }}\n\n".format(type_name, "", cs_struct_body)
        
        # Only Buffers tend to need HLSL
        if type_category in ["ConstantBuffer", "StructuredBuffer"]:
            hlsl_content += "struct {} {{\n{}}};\n\n".format(type_name, hlsl_struct_body)
            has_hlsl_data = True
            
        serialization_content += generate_serialization(type_name, fields)

    cpp_content += serialization_content
    cpp_content += "}} // namespace {}\n".format(namespace)
    cs_content += "}\n"

    # Write C++
    cpp_path = os.path.join(CPP_OUTPUT_DIR, base_name + ".h")
    with open(cpp_path, "w") as f: f.write(cpp_content)
    
    # Write HLSL (if has buffer data)
    if has_hlsl_data:
        hlsl_path = os.path.join(HLSL_OUTPUT_DIR, base_name + ".hlsli")
        with open(hlsl_path, "w") as f: f.write(hlsl_content)

    # Write C#
    cs_path = os.path.join(CS_OUTPUT_DIR, base_name + ".cs")
    with open(cs_path, "w") as f: f.write(cs_content)
    
    print("Processed {}: Generated .h, .cs{}".format(base_name, ", .hlsli" if has_hlsl_data else ""))

def generate():
    if not os.path.exists(INPUT_DIR):
        print("Error: {} not found.".format(INPUT_DIR))
        return

    yaml_files = glob.glob(os.path.join(INPUT_DIR, "*.yaml"))
    for yaml_path in yaml_files:
        process_file(yaml_path)

if __name__ == "__main__":
    generate()
