import yaml
import os

# Configuration
INPUT_FILE = "Project/Tools/schema.yaml"
CPP_OUTPUT = "Project/Schema/Schema.h"
HLSL_OUTPUT = "Project/Assets/Shader/Schema/Schema.hlsli"
CS_OUTPUT = "SubProjects/ONEngine.Scripting/Generated/Schema.cs"

TYPE_MAP_CPP = {
    "float4x4": "Engine::Math::Matrix4x4",
    "float4": "Engine::Math::Vector4",
    "float3": "Engine::Math::Vector3",
    "float2": "Engine::Math::Vector2",
    "float": "float",
    "uint32": "uint32_t",
}

TYPE_MAP_HLSL = {
    "float4x4": "float4x4",
    "float4": "float4",
    "float3": "float3",
    "float2": "float2",
    "float": "float",
    "uint32": "uint",
}

TYPE_MAP_CS = {
    "float4x4": "Matrix4x4",
    "float4": "Vector4",
    "float3": "Vector3",
    "float2": "Vector2",
    "float": "float",
    "uint32": "uint",
}

TYPE_SIZES = {
    "float4x4": 64,
    "float4": 16,
    "float3": 12,
    "float2": 8,
    "float": 4,
    "uint32": 4,
}

def generate():
    if not os.path.exists(INPUT_FILE):
        print(f"Error: {INPUT_FILE} not found.")
        return

    with open(INPUT_FILE, "r") as f:
        schema = yaml.safe_load(f)

    cpp_content = "#pragma once\n#include \"Engine/Core/Math/Math.h\"\n#include <cstdint>\n\nnamespace Engine::GeneratedSchema {\n\n"
    ecs_content = "\n} // namespace Engine::GeneratedSchema\n\nnamespace Engine::ECS {\n\n"
    hlsl_content = "// Generated by codegen.py\n\n"
    cs_content = "using System.Runtime.InteropServices;\nusing ONEngine.Scripting.Math;\n\nnamespace ONEngine.Scripting.Generated\n{\n"

    for type_name, info in schema.get("types", {}).items():
        type_category = info.get("type")
        is_cb = type_category == "ConstantBuffer"
        is_comp = type_category == "Component"
        fields = info.get("fields", [])
        
        cpp_struct_body = ""
        hlsl_struct_body = ""
        cs_struct_body = ""
        
        current_offset = 0
        pad_index = 0
        
        for field in fields:
            f_name = field["name"]
            f_type = field["type"]
            f_size = TYPE_SIZES[f_type]
            
            # アライメントチェック (16バイト境界を跨ぐ場合はパディング)
            remaining_in_chunk = 16 - (current_offset % 16)
            if f_size > remaining_in_chunk and remaining_in_chunk < 16:
                pad_size = remaining_in_chunk
                cpp_struct_body += f"    uint8_t _pad{pad_index}[{pad_size}];\n"
                hlsl_struct_body += f"    uint _pad{pad_index}[{pad_size // 4}];\n" if pad_size % 4 == 0 else f"    uint8_t _pad{pad_index}[{pad_size}];\n"
                cs_struct_body += f"    private unsafe fixed byte _pad{pad_index}[{pad_size}];\n"
                pad_index += 1
                current_offset += pad_size

            cpp_struct_body += f"    {TYPE_MAP_CPP[f_type]} {f_name};\n"
            hlsl_struct_body += f"    {TYPE_MAP_HLSL[f_type]} {f_name};\n"
            cs_struct_body += f"        public {TYPE_MAP_CS[f_type]} {f_name};\n"
            current_offset += f_size

        # 構造体全体のサイズを16バイトに切り上げ (CBやSBでの安全のため)
        if current_offset % 16 != 0:
            pad_size = 16 - (current_offset % 16)
            cpp_struct_body += f"    uint8_t _final_pad{pad_index}[{pad_size}];\n"
            hlsl_struct_body += f"    uint _final_pad{pad_index}[{pad_size // 4}];\n" if pad_size % 4 == 0 else f"    uint8_t _final_pad{pad_index}[{pad_size}];\n"
            cs_struct_body += f"    private unsafe fixed byte _final_pad{pad_index}[{pad_size}];\n"
            current_offset += pad_size

        struct_decl_cpp = f"struct {type_name} {{\n{cpp_struct_body}}};\n\n"
        struct_decl_hlsl = f"struct {type_name} {{\n{hlsl_struct_body}}};\n\n"
        struct_decl_cs = f"    [StructLayout(LayoutKind.Sequential)]\n    public struct {type_name}\n    {{\n{cs_struct_body}    }}\n\n"
        
        if is_comp:
            ecs_content += struct_decl_cpp
        else:
            cpp_content += struct_decl_cpp
        
        hlsl_content += struct_decl_hlsl
        cs_content += struct_decl_cs

    cpp_content += ecs_content + "} // namespace Engine::ECS\n"
    cs_content += "}\n"

    os.makedirs(os.path.dirname(CPP_OUTPUT), exist_ok=True)
    os.makedirs(os.path.dirname(HLSL_OUTPUT), exist_ok=True)
    os.makedirs(os.path.dirname(CS_OUTPUT), exist_ok=True)

    with open(CPP_OUTPUT, "w") as f: f.write(cpp_content)
    with open(HLSL_OUTPUT, "w") as f: f.write(hlsl_content)
    with open(CS_OUTPUT, "w") as f: f.write(cs_content)
    print(f"Generated {CPP_OUTPUT}, {HLSL_OUTPUT}, and {CS_OUTPUT}")

if __name__ == "__main__":
    generate()
